### ISSUE TITLE
Relevant heading text for each slide

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/firstrunwizard#107]
Looking at the header, it seems we should only have the main slogan on the first slide. The others can have their own text as a heading so you can more quickly see waht the slide is about:
1. **A safe home for all your data**
2. **Our values**
3. **Connect with desktop & mobile**
4. There’s an app for that … just joking. **Extend with apps**
5. **Get support or participate**

Does that seem fitting @jospoortvliet @juliushaertl?

**Comment by juliushaertl** [comment]
Makes a lot of sense :+1: From my side.
