### ISSUE TITLE
[BITV] Focus is lost to body when closing firstrunwizard

### ISSUE THREAD

**Issue by Pytal** [nextcloud/firstrunwizard#1072]
1) Open firstrunwizard from user menu
![image](https://github.com/nextcloud/firstrunwizard/assets/24800714/a1fcab02-cbcd-4662-ba1f-e5ef9c922e25)
2) Close wizard

Expected: Focus returns to user menu trigger button
Actual: Focus is lost to body

**Comment by szaimen** [comment]
Could not test this because firstrunwizard is not part of the a11y test instance...

**Comment by szaimen** [comment]
adding the label so that I don't check it everytime...
