### ISSUE TITLE
Outdated app logos

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/firstrunwizard#1297]
### Steps to reproduce
1. Open ``/settings/apps/discover``

### Expected behaviour

The welcome video in the frw and the app settings shows the new Mail logo, changed 2022: https://github.com/nextcloud/mail/pull/6944

### Actual behaviour

![Bildschirmfoto vom 2024-07-31 11-22-12](https://github.com/user-attachments/assets/679351c6-8466-4611-8027-981048123cdc)

![image](https://github.com/user-attachments/assets/4d99e580-cc6a-48d0-b2f0-56d7e33508a6)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by ChristophWurst** [comment]
@marcoambrosini do you have the sources to recreate the video with the new logo?

Ref https://github.com/nextcloud/firstrunwizard/pull/960

**Comment by ChristophWurst** [comment]
Calendar is also outdated with Hub 9: https://github.com/nextcloud/calendar/pull/6054

**Comment by AndyScherzinger** [comment]
Except for the Talk logo, all icons changed with Hub 9 (or previous) versions. According to @jancborchardt in general visuals are updated steps by step, but yes, generally makes sense to update the video - all icons are Google M3

**Comment by jancborchardt** [comment]
For reference, the assets are at https://cloud.nextcloud.com/f/9162336 (internal link). Dereck will work on updating them.


The right icons are Material Symbols:

- Files: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368&selected=Material+Symbols+Outlined:folder:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=folder
- Photos: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368&selected=Material+Symbols+Outlined:imagesmode:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=photo
- Activity: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368&selected=Material+Symbols+Outlined:bolt:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=light
- Talk: Unchanged
- Contacts: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368&selected=Material+Symbols+Outlined:group:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=people
- Calendar: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368&selected=Material+Symbols+Outlined:calendar_today:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=calendar
- Mail: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368&selected=Material+Symbols+Outlined:mail:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=mail
- Office: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.size=24&icon.color=%235f6368&selected=Material+Symbols+Outlined:description:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=document

**Comment by AndyScherzinger** [comment]
😍
