### ISSUE TITLE
Bug: the height is not the same

### ISSUE THREAD

**Issue by szaimen** [nextcloud/firstrunwizard#1342]
However noticed something else (height is not the same):
![image](https://github.com/user-attachments/assets/e29b17e8-5d09-4517-82cf-4bf011338aab)
Shall I open a new issue?

_Originally posted by @szaimen in https://github.com/nextcloud/firstrunwizard/issues/1338#issuecomment-2317166076_

**Comment by szaimen** [comment]
FYI @susnux. Shall I take a look?

**Comment by susnux** [comment]
Yes please
