### ISSUE TITLE
Arrow keys don't work anymore in first run wizard

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/firstrunwizard#147]
* expected: using the arrow keys should change the section of the wizard
* actual: using the arrow keys does not trigger anything

cc @jancborchardt @juliushaertl

**Comment by juliushaertl** [comment]
@MorrisJobke I cannot reproduce this, works fine here on chromium/ff as well as safari tested with browserstack.

**Comment by MorrisJobke** [comment]
Mmmh ... I tested with safari- let me retry

**Comment by jancborchardt** [comment]
For me it works on Chrome and FF. The only issue seems to be when you are in an app which uses the arrow keys itself. The only one I found so far is Mail. In that case it goes through mails and does not change the slides. cc @ChristophWurst 

Is it possible to prevent the app receiving the keycode and instead having it go to the first run wizard when it is open?

**Comment by juliushaertl** [comment]
Might be that the mail app is canceling the key down event somehow and therefore it never reaches the firstrunwizard.

**Comment by MorrisJobke** [comment]
Indeed - works now.
