### ISSUE TITLE
Option to show wizard again in settings

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/firstrunwizard#156]
* maybe also related to #150 

Before there was a button to open the wizard on the "mobile & desktop" page.

cc @juliushaertl

**Comment by juliushaertl** [comment]
It was removed by https://github.com/nextcloud/firstrunwizard/pull/65 since the "About" menu triggers the firstrunwizard.

**Comment by MorrisJobke** [comment]
> It was removed by #65 since the "About" menu triggers the firstrunwizard.

Gotcha 👍
