### ISSUE TITLE
First Run Wizard Displays Nextcloud Logo with Custom Theme

### ISSUE THREAD

**Issue by terrytibbles** [nextcloud/firstrunwizard#158]
### Steps to reproduce
1. apply custom theme in config.php
2. log in to Nextcloud
3. if it is a new user, the first run wizard will be displayed, otherwise go to User icon > About.

### Expected behaviour
What I would expect is that this is themed in the same way as the rest of the Nextcloud instance.

### Actual behaviour
Default Nextcloud theme displayed.

### Server configuration
**Operating system**:
Arch Linux

**Web server:**
Apache 2.4.38

**Database:**
MariaDB 10.3.12

**PHP version:**
7.2.14

**Nextcloud version:**
15.0.4

**Where did you install Nextcloud from:**
Source

**List of activated apps:**

**Nextcloud configuration:**

### Client configuration
**Browser:**
Firefox 65.0.1

**Operating system:**
macOS Sierra

#### Browser log

![nextcloud-first-run-wizard-1](https://user-images.githubusercontent.com/25575702/53144324-cc65ae00-35d6-11e9-99b2-c8d5c6495fa2.png)

**Comment by juliushaertl** [comment]
If you use a custom theme, you will need to adjust your themes stylesheet to apply the logo to the first run wizard as well. The following should work for the example theme. This is nothing we can do automatically.

```
.firstrunwizard-header .logo,
#header .logo {
	background-image: url('../img/logo.svg') !important;
	width: 256px;
	height: 128px;
}
```

**Comment by terrytibbles** [comment]
Is that in the [documentation](https://docs.nextcloud.com/server/stable/developer_manual/core/theming.html)?

**Comment by juliushaertl** [comment]
@terrytibbles I added the rule to the example theme: https://github.com/nextcloud/server/pull/14338

In general we recommend to use the theming app for easier adjustments that will have no incompatibilities on Nextcloud updates.

**Comment by terrytibbles** [comment]
What if the theme's background is different from the Nextcloud default?
