### ISSUE TITLE
Merge master and v15.x?

### ISSUE THREAD

**Issue by jernst** [nextcloud/firstrunwizard#166]
It appears there is a substantial difference between what's on master and what's being released. Could those differences be reconciled?

Specifically, @kesselb implemented PR https://github.com/nextcloud/firstrunwizard/pull/98 which was merged into master in early January, but so far it has not shown up in a Nextcloud release. It would be nice if it did :-)

While I was looking for it, I noticed the "diff" is substantial between between master and tag v15.0.5, which presumably won't get narrower the more time passes :-)

**Comment by MorrisJobke** [comment]
> Specifically, @kesselb implemented PR #98 which was merged into master in early January, but so far it has not shown up in a Nextcloud release. It would be nice if it did :-)

master is what comes to Nextcloud 16. And as the firstrunwizard is shipped in the release itself we will stick here to the stable branches as well. 

I hope that makes it clear why it wasn't pushed to the available version. Maybe in the future we will make this more independent from the server releases but as of now it is like that.
