### ISSUE TITLE
People should be prompted to input info (like mail, name etc) on first run

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/firstrunwizard#17]
@ryno83 @nextcloud/designers let's continue discussing here how that could look like. :)

**Comment by eppfel** [comment]
If we do it, it should depend on the data we not have. If the admin set up your account with all details, you don't want to be bothered, right?

**Comment by te-online** [comment]
First thing you'll see is the first-run-screen, right? 

Hence, my first idea is to add a section to the pop-up where you would be prompted for the missing stuff in your profile. The user can then decide whether they want to fill in the form now, or close the dialogue for good.

![bildschirmfoto 2016-09-20 um 18 32 47](https://cloud.githubusercontent.com/assets/4127167/18679838/9eca39d0-7f61-11e6-8694-5f2bdc3e8011.png)

However, there is not a lot of space left and I wouldn't want to put *more* information on the screen, rather then less. Personally, I feel that people don't want to spend a lot of time there – they want to get to the *real* stuff (no scientific evidence for that, though 😉 ).

So, second thought was a more subtle hint for the user, like a message on the top of the files list, when they first get there. I know, that we didn't do something like this before, but I wanted to try it anyways. 

![bildschirmfoto 2016-09-20 um 18 20 11](https://cloud.githubusercontent.com/assets/4127167/18679823/96488d70-7f61-11e6-86dd-c16e53aaddfa.png)

It might work, but I don't want to introduce a whole new way of showing messages just for this purpose. Maybe some more ideas would be great? 😄

**Comment by eppfel** [comment]
You're completely right, that we should not introduce just another modailty. We have the modal/pop-up window, notifications, and the debug/updater messages. (even more?)
I think the debug/updater messages, e.g. `one app update pending`, have to be redesigned as well, right? (They don't work on mobile.) Maybe this is just another use case for those?

Also, the placing you propose is to arbitrary imo and might not work in every app.

**Comment by eppfel** [comment]
Relevant nextcloud/server#301

**Comment by Bugsbane** [comment]
Actually there's already talk of moving the current notifications such as update notifications, to something styled just like in the original posts example. Accordingly, it wouldn't be a new way of showing notifications at all (although the buttons may require some new stuff... not sure.)

From memory, the issue anyway raised about this had a title about non-ui blocking notifications and was filed under the server component.

**Comment by jancborchardt** [comment]
I’m not sure if putting it in the first run modal is good, because there’s already so much stuff. ;) If it’s more you will just close it right away.

Some kind of overlay is good. Maybe indeed as notification (cc @nickvergessen) or as a pointer to the user menu?
And then in the Personal settings itself we could have an indicator for %-completed, or something like that. Maybe less obnoxious, but a similar idea. Also cc @schiessle cause we want to use a lot of this info for federation.

**Comment by te-online** [comment]
> I think the debug/updater messages, e.g. one app update pending, have to be redesigned as well, right? (They don't work on mobile.) Maybe this is just another use case for those?

---
> Maybe indeed as notification (cc @nickvergessen) or as a pointer to the user menu?

Could be the way to go! A notification would catch attention, but is not *blocking* like a pop-up.

> And then in the Personal settings itself we could have an indicator for %-completed, or something like that.

👍 That would be a nice visual motivation to fill in your details, but it needs to be easy to get to 100%. I mean, if your Skype-name is missing, you wouldn't want to be stuck at 80% all the time.

Also, I think there should only be one place where the user fills in their details. It could be confusing if there are multiple UIs.

**Comment by nickvergessen** [comment]
Let me have a look at the notification idea, sounds like a good way.
