### ISSUE TITLE
New 'next' buttons are too far away from content. Back button is missing styling

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/firstrunwizard#177]
The back and forward buttons are too far away from the the actual content. Especially on a big screen. See screenshot. The 'back' button is missing styling. Hint: This is using a green theme. So the color is not the bug ;-)

<img width="1932" alt="Screen Shot 2019-03-19 at 17 51 14" src="https://user-images.githubusercontent.com/867445/54639491-c952c600-4a8d-11e9-8fce-a14687953fc7.png">

**Comment by karlitschek** [comment]
@rullzer @MorrisJobke @skjnldsv @juliushaertl @jancborchardt

**Comment by MorrisJobke** [comment]
Actually the left button is the normal one and the right one the primary. This was intentional on the first run wizard. In the viewer for example both are like the left one. I remember some discussions about this last week. cc @nextcloud/designers

**Comment by skjnldsv** [comment]
> This is using a green theme. So the color is not the bug ;-)

I'm a bit disappointed that you do not use Jan's lsd app https://github.com/jancborchardt/lsd
