### ISSUE TITLE
First Run Wizard Displays Nextcloud Background with Custom Theme

### ISSUE THREAD

**Issue by terrytibbles** [nextcloud/firstrunwizard#179]
### Steps to reproduce
1. apply custom theme in config.php
2. log in to Nextcloud
3. if it is a new user, the first run wizard will be displayed, otherwise go to User icon > About.

### Expected behaviour
What I would expect is that this is themed in the same way as the rest of the Nextcloud instance.

### Actual behaviour
Although it is possible to customise the logo, the default Nextcloud background is displayed.

### Server configuration
**Operating system**:
Arch Linux

**Web server:**
Apache 2.4.38

**Database:**
MariaDB 10.3.12

**PHP version:**
7.2.14

**Nextcloud version:**
15.0.4

**Where did you install Nextcloud from:**
Source

**List of activated apps:**

**Nextcloud configuration:**

### Client configuration
**Browser:**
Firefox 65.0.1

**Operating system:**
macOS Sierra

#### Browser log

![nextcloud-first-run-wizard-1](https://user-images.githubusercontent.com/25575702/53144324-cc65ae00-35d6-11e9-99b2-c8d5c6495fa2.png)

**Comment by MorrisJobke** [comment]
cc @juliushaertl @skjnldsv

**Comment by skjnldsv** [comment]
Fixed in the newversion?

**Comment by juliushaertl** [comment]
You can overwrite the background image by applying a custom css rule for this. In general we recommend to use the theming app for this, as it provides an easy mechanism to replace the background image.

**Comment by terrytibbles** [comment]
@juliushaertl What's the code for that? Is it documented anywhere?
