### ISSUE TITLE
Access forbidden on the 'Go to Apps' link

### ISSUE THREAD

**Issue by daita** [nextcloud/firstrunwizard#180]
### Steps to reproduce
1. Create a non-admin account
2. Log in with this new account
3. Go to the 3rd tab of the First Run Wizard
4. Click the bottom link

### Expected behaviour
Link to apps.nextcloud.com ?

### Actual behaviour
Open a page on /index.php/settings/apps that returns:
```
Access forbidden
Logged in user must be an admin
```

**Comment by MorrisJobke** [comment]
cc @juliushaertl
