### ISSUE TITLE
macOS/iOS configuration profiles not available

### ISSUE THREAD

**Issue by heikobornholdt** [nextcloud/firstrunwizard#187]
### Steps to reproduce
1. Access nextcloud via HTTPS
2. Open Personal Settings/Sync clients

### Expected behaviour
Button "Download macOS/iOS configuration profile" is available

### Actual behaviour
Button "Download macOS/iOS configuration profile" is not available

This seems to be caused by a faulty TLS check [here](https://github.com/nextcloud/firstrunwizard/blob/6acfd6e586051f89ac1de11fc210c79b25bdf450/templates/personal-settings.php#L52) and [here](https://github.com/nextcloud/firstrunwizard/blob/bc23ad100226f689f8a29d260c61caeea34e43ef/lib/Controller/WizardController.php#L82).
On my webserver `getHttpProtocol()` returns `HTTP/1.1`. I suggest to change the check to something like `isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on'`.

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 16.0.0

**Where did you install Nextcloud from:**
ALL-INKL.COM Software Installer

**List of activated apps:**
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.1
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - registration: 0.4.6
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.feuerwehr-pinneberg.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.0.9",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "puQ16_",
        "mysql.utf8mb4": false,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "tempdirectory": "\/www\/htdocs\/w018d686\/***REMOVED SENSITIVE VALUE***.de\/tmp\/",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "simpleSignUpLink.shown": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Client configuration
**Browser:** Google Chrome 73.0.3683.103

**Operating system:** macOS Mojave 10.14.4

**Comment by MorrisJobke** [comment]
Fix is in #188
