### ISSUE TITLE
App is not compliant (NC 16.0.3, firstrunwizard version 2.5.0)

### ISSUE THREAD

**Issue by kimsyversen** [nextcloud/firstrunwizard#206]
I have installed Nextcloud 16.0.3 via docker image which is using firstrunwizard 2.5.0. Earlier it has been possible to modify the look of the firstrunwizard by modifying wizard.php. For an unknown reason, this do not work now. I checked the code and it seem to be some bugs:

```
www-data@0d2b56ef20b6:~/html$ php occ app:check-code firstrunwizard
Analysing /var/www/html/apps/firstrunwizard/lib/AppInfo/Application.php
 2 errors
    line   57: OC_Util - Static method of private class must not be called
    line   75: OC_Util - Static method of private class must not be called
Invalid appinfo.xml file found: Element 'default_enable': This element is not expected. Expected is one of ( category, website, discussion, bugs ).

App is not compliant
```

**Comment by bhotrock** [comment]
This isn't in response to the listed errors, but rather about modifying wizard.php.  In the past as you mentioned, editing wizard.php would allow us to display a Terms of Use page.  Upon upgrading to version 16, that quit working.  I finally found part of the solution:  edit file ./firstrunwizard/lib/Controller/WizardController.php

This allowed us to change the slide pages that are displayed.  The one thing we're still stuck on is how to change the text of the "Start using Nextcloud" button.  We've tried to change that text everywhere we can find it and the button text won't change.

Sure wish we knew why making changes in wizard.php is not changing anything.
