### ISSUE TITLE
Refused to load the image 'http://domain.ltd/apps/firstrunwizard/img/apps/mail.svg' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: https://usercontent.apps.nextcloud.com".

### ISSUE THREAD

**Issue by arkylin** [nextcloud/firstrunwizard#223]
Refused to load the image 'http://domain.ltd/apps/firstrunwizard/img/apps/mail.svg' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: https://usercontent.apps.nextcloud.com".

**Comment by raffisweb** [comment]
Same here. Is there a solution available?
NC seems to misbehave regarding https and https use. Maybe there is a config for that?


![error](https://user-images.githubusercontent.com/22199157/85920677-fb003280-b875-11ea-937b-6f8cad8e1e7c.png)

Webdav-Link is also http only. 


![error2](https://user-images.githubusercontent.com/22199157/85920709-49adcc80-b876-11ea-8fe5-c47b5a6fb128.png)

**Comment by juliushaertl** [comment]
This seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

For further bug reports please fill out the issue template.

It is most likely a missing overwriteprotocol configuration.
