### ISSUE TITLE
Firstrun video polishing

### ISSUE THREAD

**Issue by rullzer** [nextcloud/firstrunwizard#224]
We should

* Ship the video with the firstrunwizard itself. So that if the default files are modified/deleted it still works
* Also show the video on pressing about (basically the wizzard is the same in both cases).

CC: @karlitschek @juliushaertl

**Comment by juliushaertl** [comment]
I assume we then disable the video if the logo of the instance is changed in the theming app?

**Comment by jancborchardt** [comment]
> I assume we then disable the video if the logo of the instance is changed in the theming app?

Good point @juliushaertl – yes I’d say if the instance is themed, we can fall back to how the slide previously was.

**Comment by rullzer** [comment]
After discussing with @karlitschek lets not care about themed instances for now. We show the vanilla nextcloud screenshots in other places as well.

If people really want to theme it all the way then either disable the firstrunwizard or write your own.

**Comment by rullzer** [comment]
@juliushaertl probably easiest to store the video files here somehwere and just have a default get route to fetch them right?

**Comment by juliushaertl** [comment]
Ok, yes we can just put them into the firstrunwizard then. We can figure out a way to replace/disable them with theming later.
