### ISSUE TITLE
Updated app suggestions

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/firstrunwizard#225]
Some updated app suggestions so we just freshen it up every release. Including the description line:

- Tasks: Sync tasks from various devices with your Nextcloud and edit them online.
- Deck: Kanban style organization for personal planning and team projects.
- Notes: Distraction-free notes and writing.
- Social: Nextcloud becomes part of the federated social networks!
- Group folders: Admin-configured folders shared by everyone in a group.

cc @juliushaertl

**Comment by rullzer** [comment]
@jancborchardt so we kill the old ones?

I mean shoving 9 notifications in the admins face after setup might be a bit much

**Comment by jancborchardt** [comment]
> @jancborchardt so we kill the old ones?

Yes, absolutely. :) Since the old ones are now suggested during installation already. :)
