### ISSUE TITLE
wrong background color in intro video

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/firstrunwizard#253]
The final screen of the new intro video has a slightly too light blue ~(0082c9)~(0b8bc3), while the _forward_ button and the headers in the following screens have the correct Nextcloud blue ~(0b8bc3)~(0082c9)

![01](https://user-images.githubusercontent.com/1804221/71820459-6e777300-308f-11ea-9a96-1cefc23b64ad.png)

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
> have the correct Nextcloud blue (0b8bc3)

'correct' is 0082c9.
But encoding videos is probably going to mess with the colour anyway, the colour space is hard to manage (but I'm not video expert)

**Comment by wiswedel** [comment]
> 'correct' is 0082c9.

Aah, you're right. Mixed that up. Just corrected it in the OP.
However, the issue persists

**Comment by jancborchardt** [comment]
The ending screen of a newer video will have the fade as in the header, so even if there’s color issues they will not really be visible as it’s not comparable to the button on the right. :)
