### ISSUE TITLE
Should we use the CloudName as name?

### ISSUE THREAD

**Issue by JanDragon** [nextcloud/firstrunwizard#259]
Should we use instance of Start using NextCloud something like start using yourcloudname? What do you think?

https://github.com/nextcloud/firstrunwizard/blob/cfc76c6051205346621d2458c1b97a4958a11179/templates/wizard.php#L47

**Comment by JanDragon** [comment]
Something like **$theme->getName()**

**Comment by juliushaertl** [comment]
Yes, we use the theme values the slides where possible as well: https://github.com/nextcloud/firstrunwizard/blob/cfc76c6051205346621d2458c1b97a4958a11179/templates/page.intro.php#L31

Pull request welcome :wink:

**Comment by JanDragon** [comment]
Done #260

**Comment by szaimen** [comment]
Seems like this was fixed in https://github.com/nextcloud/firstrunwizard/pull/530
