### ISSUE TITLE
Do not recommend incompatible apps

### ISSUE THREAD

**Issue by J0WI** [nextcloud/firstrunwizard#261]
### Steps to reproduce
1. install new Nextcloud 18 (e.g. start new Docker container)
2. finish setup and login
3. look at the announcements

### Actual behaviour
[setAppHintDetails](https://github.com/nextcloud/firstrunwizard/blob/v18.0.0RC2/lib/Notification/Notifier.php#L155) recommends a bunch of additional apps, but some of them ([deck](https://github.com/nextcloud/deck/commit/c88b25c627eef93f90fcbb69324dae9facd8924a) and [social](https://github.com/nextcloud/social/issues/844)) are not yet marked as compatible or released for 18.

### Expected behaviour

- `setAppHintDetails` should only recommend well maintained and compatible apps
- Recommend apps should be well maintained and compatible

### Server configuration
_all defaults, doesn't really matter here_

**Comment by jancborchardt** [comment]
Deck and Social are compatible with 18 and 19 since some time, so this is solved. :)
