### ISSUE TITLE
Webserver configuration update required to serve introduction video 

### ISSUE THREAD

**Issue by kesselb** [nextcloud/firstrunwizard#273]
That's a regression from #227 

I'm using nginx for my development instance. After the first login to a new user account I see a blue page but no video. The request is redirected to /login and /files afterwards.

```
curl -I https://cloud.nextcloud.com/apps/firstrunwizard/img/Nextcloud.webm
HTTP/1.1 302 Found
Date: Sat, 18 Jan 2020 21:47:11 GMT
Server: Apache/2.4.29 (Ubuntu)
Location: https://cloud.nextcloud.com/login
```

```
curl -I https://cloud.nextcloud.com/apps/firstrunwizard/img/intro.png
HTTP/1.1 200 OK
Date: Sat, 18 Jan 2020 21:47:53 GMT
Server: Apache/2.4.29 (Ubuntu)
```

Nginx: Add mp4 and webm like below

```
location ~ \.(?:png|html|ttf|ico|jpg|jpeg|mp4|webm)$ {
    try_files $uri /index.php$request_uri;
}
```

Apache2 with pretty urls: Add mp4 and webm below

https://github.com/nextcloud/server/blob/1b46621cd31dabb48084c8e23f741de77e7007b4/lib/private/Setup.php#L523

**Comment by kesselb** [comment]
@juliushaertl @rullzer :construction_worker_man:

**Comment by rullzer** [comment]
Right.
Yes we should update the conf. Or see if we can do it with a route maybe?

**Comment by kesselb** [comment]
Webserver is faster ;) /img/ seems like a folder for static assets. If there is no need to check access right or similar we don't have to boot the application.

**Comment by juliushaertl** [comment]
Nginx config update in https://github.com/nextcloud/documentation/pull/1833
Apache in https://github.com/nextcloud/server/pull/19417 https://github.com/nextcloud/server/pull/19423
