### ISSUE TITLE
Make reminder notification to fill out profile configurable

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/firstrunwizard#35]
Since #18 a newly logged in user is reminded to fill out the profile with the following text:

> Add your profile information! :) For example your email is needed to reset your password.

This could be misleading in several ways:

1. If the password comes from LDAP the password may not be mutable 
2. If the mail address comes from LDAP it is prefilled and also immutable
3. If you want to show the first run wizard to you users but don't want to push them to fill out optional profile fields 

Hence it would be nice if this notification could be configurable or alternatively disabled when users come from LDAP.

**Comment by MorrisJobke** [comment]
Fixed in #33
