### ISSUE TITLE
Slogan used in wizard does not resolve html.

### ISSUE THREAD

**Issue by mingo3369** [nextcloud/firstrunwizard#36]
I placed a url in the slogan so I could use it as register screen on the login page.  The wizard displays the same slogan but does not resolve the link so it displays the code instead of the link.

![untitled](https://cloud.githubusercontent.com/assets/8374601/24117253/7d92882c-0d77-11e7-988a-60c823c59d9f.png)

**Comment by MorrisJobke** [comment]
@LukasReschke I guess this is by intention, right?

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/server/pull/3868 and cc @nickvergessen

**Comment by nickvergessen** [comment]
Yes its by intention.
Only HTMLName is allowed to contain HTML

**Comment by MorrisJobke** [comment]
> Only HTMLName is allowed to contain HTML

I guess in this case it is done via the theming app, which doesn't have that attribute.

**Comment by nickvergessen** [comment]
You can use html in the name there, it will be stripped for except the html name
