### ISSUE TITLE
Icon for "Add your profile information" notification

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/firstrunwizard#362]
The app recommendations all have icons, but the "Add your profile information" notification doesn’t have any. The most fitting one would simply be `icon-user`.

![image](https://user-images.githubusercontent.com/925062/88054728-1cdf9300-cb5e-11ea-95e7-86fa20730596.png)

I assume this will have to be done somewhere in https://github.com/nextcloud/firstrunwizard/blob/master/lib/Notification/Notifier.php, but if @juliushaertl or someone points out the correct place, this would be a good first issue. :)

**Comment by juliushaertl** [comment]
Yes, basically you need to set an icon for the notification https://github.com/nextcloud/firstrunwizard/blob/master/lib/Notification/Notifier.php#L102 as it is done here for the apps https://github.com/nextcloud/firstrunwizard/blob/master/lib/Notification/Notifier.php#L201-L203
