### ISSUE TITLE
wrong dutch spelling

### ISSUE THREAD

**Issue by JK74** [nextcloud/firstrunwizard#45]
NCS12.0.2:
see screenshow below. the word '**em**' should be 'en'
![image](https://user-images.githubusercontent.com/17946255/29622432-b7f2ddf6-8823-11e7-82c9-109402c582ec.png)

**Comment by MorrisJobke** [comment]
updated - cc @rullzer @icewind1991 @jospoortvliet just to be sure, that the dutch string is correct. 😉

**Comment by JK74** [comment]
@MorrisJobke @jospoortvliet I changed some files on transifex yesterday but I'm not sure if that is a valid way as done yesterday? I did review as well and did try to add a tag reviewed to the 243 items but still they showed up as unreviewed. Am I doing something wrong or is the tooling not meeting my expectations in intuitive way of working

**Comment by jospoortvliet** [comment]
It might be that your account has no right to review but - I'm no transifex expert...
