### ISSUE TITLE
Option to disable pages of first run wizard

### ISSUE THREAD

**Issue by D1StrX** [nextcloud/firstrunwizard#452]
**Enhancement for the customization options**
Trying to customize the first run pages. So far that worked out for every page, except: page.intro.php

I want to disable that page. Renaming the php file didn't work. Completely redesigning it with java (zero nodejs knowledge) is overkill, if just be able to disable that page would do the trick.

Hopefully this could be implemented or explained how to do this, it makes the first run wizard a little bit more personalized. 

*Small other question:*
Where is the code located for the text "Start using Nextcloud" button right bottom at the end of the wizard?

**Comment by juliushaertl** [comment]
Already possible with https://github.com/nextcloud/firstrunwizard/pull/386
