### ISSUE TITLE
First Run Wizard Displays Nextcloud Logo with Custom Theme

### ISSUE THREAD

**Issue by terrytibbles** [nextcloud/firstrunwizard#48]
Hello,

When the themes are updated manually using the instructions [here](https://docs.nextcloud.com/server/12/developer_manual/core/theming.html), logging in for the first time still displays the Nextcloud logo and background (see attached).

Thanks.

![first-run-wizard-nextcloud-1](https://user-images.githubusercontent.com/25575702/30362428-9b5540be-988e-11e7-8b61-af5a0f7e90c6.png)

**Comment by MorrisJobke** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
You need to overwrite the styles for the firstrun wizard in your custom theme for that:
https://github.com/nextcloud/firstrunwizard/blob/master/css/firstrunwizard.css#L9-L26

I guess we need to make some adjustments to the example theme, so the firstrun wizard is themed with that as well.

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/firstrunwizard/pull/57 since I moved to SCSS there and use the logo/background from the theming app now.

**Comment by terrytibbles** [comment]
This is a problem in Nextcloud 14. Do the styles still need to be updated?



> You need to overwrite the styles for the firstrun wizard in your custom theme for that:
> https://github.com/nextcloud/firstrunwizard/blob/master/css/firstrunwizard.css#L9-L26
> 
> I guess we need to make some adjustments to the example theme, so the firstrun wizard is themed with that as well.

Is there a working link for this?

**Comment by terrytibbles** [comment]
This is still a problem in Nextcloud 15.

**Comment by juliushaertl** [comment]
@terrytibbles Works fine here, if you still have issues, please open a new bug report with some more details about your setup.
