### ISSUE TITLE
Button to close the wizard vanishes

### ISSUE THREAD

**Issue by varac** [nextcloud/firstrunwizard#488]
We run [behave tests](https://open.greenhost.net/openappstack/openappstack/-/jobs/67349) to test Nextcloud functionality in automated installations. After upgrading to a newer NC version (and I guess with that to a newer version of firstrunwizard) the tests failed because the selector class of the button to close the wizard changed. What makes it even harder/impossible (?) to select it properly is that it vanishes after a few seconds. Is there a possibility to restore the old behaviour so integration tests are easier to implement ?

**Comment by juliushaertl** [comment]
Yes, we switched to a unified vue component for the modal dialog, but that should offer to provide a 0 timeout to always keep the close button visible in the first run wizard.
https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Modal/Modal.vue#L430-L435

@jancborchardt I think that makes sense for the firstrunwizard to always show the close, right?

**Comment by varac** [comment]
Nevermind, I realized you can close the modal by pressing `esc` which works for us just fine !
