### ISSUE TITLE
Nextcloud logo missing using 13.0 beta 1

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/firstrunwizard#50]
<img width="1069" alt="bildschirmfoto 2017-12-03 um 16 21 27" src="https://user-images.githubusercontent.com/19711361/33526766-18491c20-d846-11e7-9cd9-b6d02d02b0c3.png">

**Comment by MorrisJobke** [comment]
Are you sure you used the correct version, because I fixed that some weeks before: #49 

Or is this the release?

**Comment by MariusBluem** [comment]
Well ... I was testing the beta bundle - Seems to be fixed :)
