### ISSUE TITLE
Nextcloud does wrongly encode the Slogan

### ISSUE THREAD

**Issue by marbetschar** [nextcloud/firstrunwizard#552]
We are able to define a slogan in the theming section of Nextcloud. Unfortunately this is displayed wrong to new users due to encoding errors.

Also, you can already see it's a bit broken when you set the slogan to 'foo & bar', and then just reload the settings page. It does not display & and instead displays &amp; as the slogan.

<img width="1424" alt="1" src="https://user-images.githubusercontent.com/392542/33878475-d1df5dca-df2b-11e7-964e-093e8dbfa84d.png">

<img width="1435" alt="2" src="https://user-images.githubusercontent.com/392542/33878482-d6aad4d8-df2b-11e7-87a4-a4bae08f95e8.png">

![3](https://user-images.githubusercontent.com/392542/33878499-deb8ba5a-df2b-11e7-9fe3-af6874acc3dc.png)

**Comment by szaimen** [comment]
Maybe a fix like https://github.com/nextcloud/server/pull/27912 would be possible here too?

**Comment by hatelamers** [comment]
the issue still persists as of 24-11-2023 in Nextcloud 27.1.3: everywhere slogan is shown, it renders special characters incorrectly
' -> &#039;
" -> &quot;
& -> &amp;

**Comment by susnux** [comment]
This is not included in 28 and for 27 it works, see it shows "Foo & Bar":

![image](https://github.com/nextcloud/firstrunwizard/assets/1855448/1d9d8aa4-8b63-403a-8e27-c5395f3a28cc)
