### ISSUE TITLE
Crashes IE 11

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/firstrunwizard#6]
<img width="1432" alt="bildschirmfoto 2016-07-27 um 16 51 33" src="https://cloud.githubusercontent.com/assets/245432/17179696/63be7a58-541a-11e6-850d-1a6ccbbf1825.png">
- login as user for the first time with first run wizard enabled
## expected

first run wizard shows up
## actual

no first run wizard but an error in the JS console: `Unexpected call to method or property access`

This is only in IE 11 and not in Edge.

**Comment by jancborchardt** [comment]
Any idea here @nextcloud/javascript?

**Comment by juliushaertl** [comment]
I cannot reproduce this anymore, let's close it.
