### ISSUE TITLE
Add about section

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/firstrunwizard#62]
As proposed by @karlitschek in #57 an about section should be added to the settings menu, to explain Nextcloud and our missing better to users. 

I would just show the first run wizard again in case the user clicks that about link or should we add a separate page to give some more detailed information about Nextcloud there?

cc @nextcloud/designers @jospoortvliet

**Comment by karlitschek** [comment]
@juliushaertl I think it is fine to just show the first run wizard again. All the information has to be in there anyways.

**Comment by juliushaertl** [comment]
Implemented in #63
