### ISSUE TITLE
Wrong display of special characters in First Run Wizard

### ISSUE THREAD

**Issue by binarybear-de** [nextcloud/firstrunwizard#67]
Some special characters are shown as ASCII-Code (e.g. ' as ASCII#39).
Original Slogan was "There is no cloud, just someone else**'**s computer
On the bottom of the login page it is working probably.

Nextcloud 13.0.2 on Debian9.4 with Apache2.4.25 and PHP7.0 (all latest under Debian Stable)
Installation as Zip-Download. Issue shows off right after initial setup.
![40284668-17d8d7ae-5c93-11e8-996d-9cfe80889cb4](https://user-images.githubusercontent.com/28809880/40576803-a11825e8-60fc-11e8-8d66-e4f306f85417.PNG)

**Comment by MorrisJobke** [comment]
Looks like double encoding. cc @skjnldsv

**Comment by MorrisJobke** [comment]
@juliushaertl 🏓
