### ISSUE TITLE
Don't show menu item if slides are disabled

### ISSUE THREAD

**Issue by danir-de** [nextcloud/firstrunwizard#708]
When setting the app not to show any slides, the "About" menu item is still showing - but it's not doing anything.

If the app setting `slides` is empty, the menu item shouldn appear.

> The intro video slide is not cutomizable through that but can be disabled with removing it from the slide list with the following config:
> 
> 	occ config:app:set firstrunwizard slides --value="values,apps,clients,final"
> 
> _Originally posted by @juliushaertl in https://github.com/nextcloud/firstrunwizard/issues/470#issuecomment-770746778_

**Comment by szaimen** [comment]
You can simply disable the app which will disable the entry, too or is there some other functionality that this app provides that you need?

**Comment by danir-de** [comment]
>  is there some other functionality that this app provides that you need?

Yes, an important part of the app is the integration of the personalized Apps and Integrations page in the settings.
Users can find all apps there as well as the url they should use as server url.

That page really helps with communicating where to find the apps and with what settings.
