### ISSUE TITLE
Setup Psalm CI

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/firstrunwizard#744]
Psalm and the OCP package are already there, but it is not run on CI

**Comment by Tas-sos** [comment]
Do you mean on GitHub actions here : https://github.com/nextcloud/firstrunwizard/tree/master/.github/workflows ?

**Comment by nickvergessen** [comment]
Yes. There are some more files needed like `psalm.xml`, `tests/psalm-baseline.xml` and composer with the package and commands.
