### ISSUE TITLE
First run wizard moves buttons around...

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/firstrunwizard#76]
The nice looking first-run-wizard moves its next button around on every click on it - that isn't really nice... @nextcloud/designers

**Comment by juliushaertl** [comment]
Yes, makes sense. I'll have a look.

**Comment by jancborchardt** [comment]
We could also possibly move the buttons to the sides? "Back" button to the left and "Next" button to the right and make them circular, maybe even with arrow inside?

**Comment by juliushaertl** [comment]
Fixed with #106
