### ISSUE TITLE
first run wizard image broken/showing the wrong image

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/firstrunwizard#785]
### Steps to reproduce
1. open the first run wizard ('about' in the personal menu)
2. go to the 2nd slide
3. see image:

<img width="1118" alt="Screenshot_20221125_215237" src="https://user-images.githubusercontent.com/551757/204054599-d5365c6f-3907-4a0d-8afa-7179e196ee8b.png">

### Expected behaviour
image should have Nextcloud blue background on top?

### Actual behaviour
my chosen background is used.

### Server configuration
25.0.2RC1 from cloud.nextcloud.com

**Comment by szaimen** [comment]
I think it is intended that the background image is shown here
