### ISSUE TITLE
Open links in new tab

### ISSUE THREAD

**Issue by daita** [nextcloud/firstrunwizard#79]
The new popup is great, however, clicking a link break UX as it open the link in the same page. Coming back does not display the popup anymore. User might feel loosing something.

Expected behavior: open each link from the popup in a new tab.

**Comment by daita** [comment]
Just found a way to display the popup: using the About link from the menu. I keep thinking it breaks the First UX

**Comment by MorrisJobke** [comment]
cc @juliushaertl @skjnldsv

**Comment by MorrisJobke** [comment]
I put it in 14.0.1

**Comment by jancborchardt** [comment]
Right! We need target="_blank" on all the external links. :)
