### ISSUE TITLE
Add version number to the first run wizard?

### ISSUE THREAD

**Issue by schiessle** [nextcloud/firstrunwizard#82]
I'm not sure if it just me, but since we have the "About" link at the top right menu I always click it if I want to find the current version of my Nextcloud installation. Probably because the "About" Dialog is the place for this information in 99% of all apps out there.

Therefore I wonder if it would make sense to add the version number to the first run wizard, somewhere? I'm not sure which would be a good place for it, but maybe @nextcloud/designers have a good idea?

**Comment by jancborchardt** [comment]
It doesn’t really make sense in the first run wizard, because it is a _first run wizard_. ;) I do agree that maybe for the "About" window we should also cut the first slide, which is just a presentation image. (Should stay in the first run wizard of course.)

But also, the version is already in the admin settings, and that is the relevant place, no?

**Comment by schiessle** [comment]
> It doesn’t really make sense in the first run wizard, because it is a first run wizard. ;) I do agree that maybe for the "About" window we should also cut the first slide, which is just a presentation image. (Should stay in the first run wizard of course.)

Or have a dedicated about page, unrelated to the first run wizard.

But as long as the first run wizard is the about dialog I think we should add it there. Having it in the first run wizard might be also a nice confirmation for the admin after installation that he is running the right version and everything was correct.

> But also, the version is already in the admin settings, and that is the relevant place, no?

I don't think so. Ask yourself where you click on all the other mobile apps, desktop apps, web apps etc you use if you want to find out which version you are running? Most likely it is always the "About" page and not somewhere in the settings.

**Comment by jancborchardt** [comment]
Ok, we can add it as greyed text somewhere on the first slide after the image. Or permanently below the dot indicators for the slides, greyed like "Nextcloud 14.1.3" or so. Do you want to submit a pull request for that? I can adjust the position if needed.

> might be also a nice confirmation for the admin after installation that he is running the right version

There’s not only male admins. :)
