### ISSUE TITLE
First Run Wizard window doesn't show up correctly. Wrong size

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/firstrunwizard#88]
### Steps to reproduce
1. install nightly master build
2. log in first time
3. broken wizard

### Expected behaviour
the wizard should show up in the right size

### Actual behaviour
wrong size
Buttons are also wrongly aligned 

### Server configuration

**Operating system**:
ubuntu

**Web server:**
apache

**Database:**
sqlite

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
nightly

**Where did you install Nextcloud from:**
nightly

**List of activated apps:**
default

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by MorrisJobke** [comment]
@karlitschek A screenshot would be nice in such cases. 😉

**Comment by karlitschek** [comment]
I know I know. This happened on two days bit not on the third. Maybe a timing problem that the window resized wrongly when the loading of the big picture on the first problem was slow. Maybe the real fix is to not resize the windows at all and always have a fixed size?? @jancborchardt

**Comment by jancborchardt** [comment]
This could be an image loading problem or a JS issue with that lightbox plugin. Any idea @juliushaertl?

**Comment by juliushaertl** [comment]
Yes, probably a timing issue. I'll have a look if we can make this a bit more stable.

**Comment by rullzer** [comment]
@juliushaertl is this also fixed with your improvements?

**Comment by juliushaertl** [comment]
Yes, we properly scale depending on the browser window with CSS now. No javascript involved, so it scales up nicely no matter when you resize the window.
